class Emojis:
    # ─── Status / General ───
    SUCCESS   = "✅"
    ERROR     = "❌"
    WARNING   = "⚠️"
    INFO      = "ℹ️"
    LOADING   = "⏳"
    ON        = "🟢"
    OFF       = "🔴"
    ENABLED   = "✅"
    DISABLED  = "❌"

    # ─── Arrows ───
    ARROW       = "➤"
    ARROW_RIGHT = "▶️"
    ARROW_LEFT  = "◀️"

    # ─── Navigation (Pagination) ───
    FIRST  = "⏮️"
    PREV   = "◀️"
    DELETE = "🗑️"
    NEXT   = "▶️"
    LAST   = "⏭️"

    # ─── Server / Info ───
    CHANNEL   = "#️⃣"
    CATEGORY  = "🗂️"
    EMOJI     = "😀"
    BOOST     = "🚀"
    ROLE      = "📍"
    SETTINGS  = "⚙️"
    MEMBERS   = "👥"
    OWNER     = "👑"
    CREATED   = "📅"
    SHIELD    = "🛡️"
    BOT       = "🤖"
    ID        = "🆔"
    SERVER    = "🏠"
    GLOBE     = "🌐"

    # ─── Moderation ───
    BAN     = "🔨"
    KICK    = "👢"
    MUTE    = "🔇"
    UNMUTE  = "🔊"
    LOCK    = "🔒"
    UNLOCK  = "🔓"
    HIDE    = "🙈"
    UNHIDE  = "👁️"
    MOD     = "🛠️"
    WARN    = "⚠️"
    NUKE    = "💣"
    PURGE   = "🧹"
    NICK    = "🏷️"
    SNIPE   = "🎯"

    # ─── Module Icons ───
    AI            = "🤖"
    ANTINUKE      = "🛡️"
    AUTOMOD       = "⚒️"
    AUTONICK      = "🎭"
    AUTORESPONDER = "⭐"
    AUTOREACT     = "💫"
    BIRTHDAY      = "🎉"
    CONFIG        = "⚙️"
    CUSTOMROLE    = "🎨"
    FUN           = "🎮"
    GAMES         = "🎲"
    GIVEAWAY      = "🎁"
    INFORMATION   = "🔧"
    INVITES       = "🤝"
    JOINTOCREATE  = "📞"
    LEVELING      = "📊"
    LOGS          = "📂"
    MUSIC         = "🎵"
    ROLEGUARD     = "🔐"
    SELFROLE      = "🆔"
    STAT          = "📈"
    TICKET        = "🎫"
    VOICE         = "🎙️"
    WELCOMER      = "👋"
    PREMIUM       = "💎"
    MODERATION    = "🛠️"
    COUNTING      = "🔢"

    # ─── Fun Commands ───
    CUTE      = "😍"
    DARE      = "🎯"
    TRUTH     = "🤔"
    HACK      = "💻"
    GAY       = "🏳️‍🌈"
    HUG       = "🤗"
    IQ        = "🧠"
    DOG       = "🐕"
    QR        = "🔳"
    QUOTE     = "💬"
    HELLO     = "👋"
    LOVE      = "💘"
    HEART     = "💖"
    SLAP      = "👋"
    SLOTS     = "🎰"
    KEY       = "🔑"
    TRANSLATE = "🌍"
    WEATHER   = "☁️"
    WIZZ      = "🪄"
    CRASH     = "💢"
    SPARKLE   = "✨"

    # ─── Music ───
    NOTE     = "🎵"
    NOTES    = "🎶"
    PLAY     = "▶️"
    PAUSE    = "⏸️"
    STOP     = "⏹️"
    SKIP     = "⏭️"
    PREVIOUS = "⏮️"
    SHUFFLE  = "🔀"
    LOOP     = "🔁"
    VOLUME   = "🔊"
    QUEUE    = "📜"

    # ─── Selfrole / Panel ───
    PANEL    = "🛠️"
    BUTTON   = "🔘"
    DROPDOWN = "🔽"
    REACTION = "⭐"
    LIST     = "📋"

    # ─── Logs ───
    LOG_MSG_DEL   = "🗑️"
    LOG_MSG_EDIT  = "📝"
    LOG_JOIN      = "📥"
    LOG_LEAVE     = "📤"
    LOG_BAN       = "🔨"
    LOG_UNBAN     = "🔓"
    LOG_KICK      = "👢"
    LOG_ROLE_ADD  = "➕"
    LOG_ROLE_REM  = "➖"
    LOG_NICK      = "🏷️"
    LOG_CHANNEL   = "📺"
    LOG_VOICE     = "🎙️"
    LOG_SERVER    = "🏠"
    LOG_INVITE    = "🔗"
    LOG_BULK_DEL  = "📦"
    LOG_TIMEOUT   = "⏰"
    LOG_BOOST     = "🚀"
    LOG_THREAD    = "🧵"
    LOG_WEBHOOK   = "🪝"
    LOG_AUTOMOD   = "⚒️"

    # ─── Games ───
    NUMBER   = "🔢"
    TROPHY   = "🏆"
    CORRECT  = "✅"
    WRONG    = "❌"
    STREAK   = "🔥"

    # ─── Misc ───
    DIAMOND = "💎"
    FIRE    = "🔥"
    STAR    = "⭐"
    CROWN   = "👑"
    BELL    = "🔔"
    LINK    = "🔗"
    CHECK   = "✔️"
    CROSS   = "✖️"
    CLOCK   = "🕐"
    PENCIL  = "✏️"
    INBOX   = "📥"
    OUTBOX  = "📤"
    PIN     = "📌"
    TAG     = "🏷️"
    TOOLS   = "🧰"

    # ─── Customrole / Setup ───
    SETUP        = "⚔️"
    GIRL         = "👧"
    BOY          = "👦"
    GUEST        = "🎫"
    VIP          = "💎"
    OFFICIAL     = "📜"

    # ─── Birthday ───
    GIFT         = "🎁"
    CAKE         = "🍰"
    PARTY        = "🥳"
    BALLOON      = "🎈"
    CONFETTI     = "🎊"
    CALENDAR     = "📅"

    # ─── Voice Commands ───
    VOICE_REC      = "🔴"
    VOICE_BAN      = "🚫"
    VOICE_DEAF     = "🔇"
    VOICE_HIDE     = "🙈"
    VOICE_KICK     = "👢"
    VOICE_LIST     = "📋"
    VOICE_LOCK     = "🔒"
    VOICE_MOVE     = "↔️"
    VOICE_MUTE     = "🔇"
    VOICE_PULL     = "🫳"
    VOICE_PUSH     = "🫴"
    VOICE_REQUEST  = "📞"
    VOICE_ROLE     = "📍"
    VOICE_UNBAN    = "✅"
    VOICE_UNDEAF   = "🔊"
    VOICE_UNHIDE   = "👁️"
    VOICE_UNLOCK   = "🔓"
    VOICE_UNMUTE   = "🔊"
    VOICE_PANEL    = "🎛️"
    VOICE_MIC      = "🎙️"

    # ─── Leveling ───
    LEVEL          = "📊"
    XP             = "✨"
    RANK           = "🏆"
    LEADERBOARD    = "🥇"
    LEVEL_UP       = "🎉"
    GOLD           = "🥇"
    SILVER         = "🥈"
    BRONZE         = "🥉"

    # ─── Giveaway ───
    GIFT_NEW    = "🎁"
    TADA        = "🎉"
    TIMER       = "⏱️"
    HOST        = "👑"
    USERS       = "👥"
    PARTICIPATE = "🎉"   # Reaction emoji for joining giveaway

    # ─── VoiceMaster (JTC) ───
    VM_LOCK     = "🔒"
    VM_UNLOCK   = "🔓"
    VM_HIDE     = "🙈"
    VM_UNHIDE   = "👁️"
    VM_RENAME   = "✏️"
    VM_LIMIT    = "🔢"
    VM_MUTE     = "🔇"
    VM_UNMUTE   = "🔊"
    VM_DEAFEN   = "🎧"
    VM_UNDEAFEN = "🎶"
    VM_PERMIT   = "✅"
    VM_BAN      = "🚫"
    VM_TRANSFER = "🔄"
    VM_CLAIM    = "👋"

    # ─── Tracker ───
    MSG_TRACK   = "💬"
    INVITE_TRK  = "🔗"
    USER_TRK    = "👤"
    STATS_TRK   = "📊"
    TRASH       = "🗑️"
    BLOCK       = "🚫"
    DOT         = "•"


    WELCOME_WAVE      = "👋"
    WELCOME_STAR      = "✨"
    WELCOME_HEART     = "💖"
    WELCOME_PARTY     = "🎉"
    WELCOME_NEW       = "🆕"
    WELCOME_MEMBER    = "👤"
    WELCOME_JOIN      = "📥"
    WELCOME_LEAVE     = "📤"
    WELCOME_GOODBYE   = "👋"
    WELCOME_BANNER    = "🖼️"
    WELCOME_THUMB     = "🖼️"
    WELCOME_COLOR     = "🎨"
    WELCOME_PREVIEW   = "👁️"
    WELCOME_EDIT      = "✏️"
    WELCOME_TEMPLATE  = "📋"
    WELCOME_WIZARD    = "🪄"
    WELCOME_DISABLE   = "🚫"
    WELCOME_ENABLE    = "🔛"
    TICKET_OPEN       = "🎫"
    TICKET_CLOSE      = "🔒"
    TICKET_REOPEN     = "🔓"
    TICKET_CLAIM      = "✋"
    TICKET_UNCLAIM    = "🤚"
    TICKET_NOTIFY     = "🔔"
    TICKET_CALL       = "📞"
    TICKET_DELETE     = "🗑️"
    TICKET_PANEL      = "📋"
    TICKET_TRANSCRIPT = "📄"
    TICKET_LOG        = "📂"
    TICKET_ARCHIVE    = "📦"
    TICKET_SUPPORT    = "🎧"
    TICKET_STAFF      = "👮"
    TICKET_USER       = "👤"
    TICKET_CATEGORY   = "🗂️"
    TICKET_RENAME     = "✏️"
    TICKET_ADD        = "➕"
    TICKET_REMOVE     = "➖"
    TICKET_NEW        = "🆕"
    TICKET_ISSUE      = "📝"
    TICKET_PRIORITY   = "⚡"
    TICKET_LOCK       = "🔐"
    TICKET_WIZARD     = "🪄"
    TICKET_AUTO       = "⚡"
    TICKET_MANUAL     = "🛠️"
    TICKET_DROPDOWN   = "🔽"
    TICKET_BUTTON     = "🔘"
    TICKET_DEPLOY     = "🚀" 
    STAFF       = "👮"
    TRANSCRIPT  = "📄"
    AN_SHIELD       = "🛡️"
    AN_WALL         = "🧱"
    AN_PROCEED      = "✅"
    AN_STOP         = "🛑"
    AN_AGREE        = "📜"
    AN_RUNNING      = "⏳"
    AN_PENDING      = "⌛"
    AN_DONE         = "✅"
    AN_FAILED       = "❌"
    AN_PROGRESS     = "▬"
    AN_NIGHT        = "🌙"
    AN_VERIFY       = "🔐"
    AN_VANITY       = "🔗"
    AN_EXTRA_OWNER  = "👑"
    AN_WHITELIST    = "✅"
    AN_UNWHITELIST  = "❌"
    AN_HOOK         = "🪝"
    AN_LOGS         = "📂"
    AN_INIT         = "⚙️"
    AN_PUNISH       = "⚡"

    # ─── AUTOMOD MODULES ───
    AM_SPAM         = "💬"
    AM_CAPS         = "🔠"
    AM_LINK         = "🔗"
    AM_INVITE       = "📨"
    AM_MENTION      = "📢"
    AM_EMOJI        = "😀"
    AM_TOKEN        = "🔑"
    AM_BADWORD      = "🤬"
    AM_OWNER        = "👑"
    AM_SCAM         = "🎣"
    AM_THRESHOLD    = "📊"
    AM_PUNISH_MUTE  = "🔇"
    AM_PUNISH_KICK  = "👢"
    AM_PUNISH_BAN   = "🔨"
    AM_PUNISH_WARN  = "⚠️"
    AM_PUNISH_DEL   = "🗑️"